---

- name: install pip
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - python-pip
    - python3-pip

- name: install docker dependencies
  apt: name={{item}} state=present
  with_items: "{{docker_dependencies}}"

- name: install tensorflow dependencies
  apt: name={{item}} state=present
  with_items: "{{tensorflow_dependencies}}"

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present

- name: install docker
  apt:
    name: docker-ce
    update_cache: yes

- name: install docker-py
  pip:
    name: docker-py
    state: present

- name: install python3 packages
  pip: name={{item}} state=present executable=pip3
  with_items: "{{python_packages}}"

- name: upload sentiment analyzer
  copy:
    src: model
    dest: /home/ubuntu

- name: upload shell script
  copy:
    src: start.sh
    dest: /home/ubuntu/start.sh

- name: upload harvester
  copy:
    src: Twitter_harvester.py
    dest: /home/ubuntu/Twitter_harvester.py

- name: pull and run mongodb container
  docker_container:
    name: my-mongo
    image: mongo
    state: started
    ports: 27017:27017
    volumes: /mnt/mntpt/db:/data/db
    command: mongod --replSet rip
